name: CI

env:
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME  }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD  }}
#  SPRING_PROFILES_ACTIVE: ci
#  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
#  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
#  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows for more
    - cron:  '30 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

#       - name: Run
#         run: $GITHUB_WORKSPACE/.github/workflows/run.sh
